# EP 3. NumPy Study
- NumPy란 무엇일까
- NumPy가 왜 필요할까
- NumPy 배워보기
- Wrap-Up

In [6]:
import numpy as np
np.__version__

'1.17.2'

# NumPy 란 무엇일까

1. 일반 목적용 프로그래밍 언어를 통계용 프로그래밍 언어처럼 쓸 수 있게 해 줌
  1. 통계나 수치분석에 적합한 자료형을 제공함
  1. 통계나 수치분석에 적합한 함수들을 제공함
1. 느려터진 파이썬에 숨통이 트일만한 속도를 제공해줌
1. 솔까말, 넘파이 없었으면 파이썬 ㅈㅂ

<img src="machine_learning_libraries.png"/>

# NumPy 가 왜 필요할까?

## 통계용 언어와 일반 목적용 언어의 근본적인 차이점  
- [1, 2, 3] + [4, 5, 6]의 값은?
- [2, 4, 6] + 2 의 값은?

In [130]:
# 일반 목적용 Python은 이렇게 답한다

a = [1, 2, 3]
b = [4, 5, 6]

c = a + b
print(c)

c = c + [2]
print(c)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 2]


## 상황에 과몰입하기

어느 날 갑자기 상무님이 부르셨다  
우리 담당의 LCP 평가의 산출 근거가 담긴 엑셀 파일을 주시며,  
각 산출 근거별로 평균 값을 지금 이 자리에서 알고 싶다고 하셨다.  

산출 근거는 개발언어/모델링/근속연차 등등 총 20가지의 항목이 있었고  
담당 인원은 200명이었다.  
어찌어찌해서 엑셀 자료를 파이썬 2차원 데이터로까지는 로딩할 수 있었는데,  
과연 어떻게 평균을 구할 수 있을까!  

위기탈출 넘파이!!  

In [36]:
data = []
np.random.seed(0)

for cnt in range(200):
    data.append(list(np.random.randint(100, size=20)))
    
for row in data:
    print(row)

[44, 47, 64, 67, 67, 9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39, 87, 46, 88]
[81, 37, 25, 77, 72, 9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19, 19, 14]
[39, 32, 65, 9, 57, 32, 31, 74, 23, 35, 75, 55, 28, 34, 0, 0, 36, 53, 5, 38]
[17, 79, 4, 42, 58, 31, 1, 65, 41, 57, 35, 11, 46, 82, 91, 0, 14, 99, 53, 12]
[42, 84, 75, 68, 6, 68, 47, 3, 76, 52, 78, 15, 20, 99, 58, 23, 79, 13, 85, 48]
[49, 69, 41, 35, 64, 95, 69, 94, 0, 50, 36, 34, 48, 93, 3, 98, 42, 77, 21, 73]
[0, 10, 43, 58, 23, 59, 2, 98, 62, 35, 94, 67, 82, 46, 99, 20, 81, 50, 27, 14]
[41, 58, 65, 36, 10, 86, 43, 11, 2, 51, 80, 32, 54, 0, 38, 19, 46, 42, 56, 60]
[77, 30, 24, 2, 3, 94, 98, 13, 40, 72, 19, 95, 72, 26, 66, 52, 67, 61, 14, 96]
[4, 67, 11, 86, 77, 75, 56, 16, 24, 29, 21, 25, 80, 60, 61, 83, 33, 32, 70, 85]
[31, 13, 71, 56, 24, 79, 41, 18, 40, 54, 79, 11, 38, 93, 1, 95, 44, 88, 24, 67]
[82, 3, 76, 35, 86, 61, 69, 87, 43, 32, 11, 84, 10, 54, 37, 28, 2, 27, 83, 89]
[23, 53, 51, 46, 20, 53, 29, 67, 35, 39, 9, 73, 41,

In [50]:
%%timeit

sum_each = []
first_round = True

for row in data:
    
    if first_round:
        for col in range(20):
            sum_each.append(row[col])
            
        first_round = False
        
    else:
        for col in range(20):
            sum_each[col] += row[col]

total_observ = len(data)
mean_each = []
for col in range(20):
    mean_each.append(sum_each[col]/total_observ)


2.58 ms ± 381 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
for i, m in enumerate(mean_each):
    print(f'{i+1} th mean: {m}')

1 th mean: 47.83
2 th mean: 46.48
3 th mean: 49.675
4 th mean: 49.325
5 th mean: 46.52
6 th mean: 45.265
7 th mean: 50.375
8 th mean: 48.04
9 th mean: 48.195
10 th mean: 49.79
11 th mean: 46.185
12 th mean: 49.46
13 th mean: 47.865
14 th mean: 48.88
15 th mean: 46.705
16 th mean: 47.33
17 th mean: 52.04
18 th mean: 53.13
19 th mean: 51.905
20 th mean: 49.25


In [58]:
np.random.seed(0)
data = np.random.randint(100, size=(200,20))

In [90]:
%%timeit

mean_each = np.add.reduce(data)/200

12.1 µs ± 999 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [92]:
for i, avg in enumerate(mean_each):
    print(f'{i+1} th mean: {avg}')

1 th mean: 47.83
2 th mean: 46.48
3 th mean: 49.675
4 th mean: 49.325
5 th mean: 46.52
6 th mean: 45.265
7 th mean: 50.375
8 th mean: 48.04
9 th mean: 48.195
10 th mean: 49.79
11 th mean: 46.185
12 th mean: 49.46
13 th mean: 47.865
14 th mean: 48.88
15 th mean: 46.705
16 th mean: 47.33
17 th mean: 52.04
18 th mean: 53.13
19 th mean: 51.905
20 th mean: 49.25


# NumPy 배워보기

## 1. list != array
__리스트는 편하지만 비효율적이다, 더 나은 데이터 타입을 달라!__

<img src="array_vs_list.png"/>

In [86]:
L = list([int(1), 'a', True, None, 3.45, 1])

for item in L:
    print(hex(id(item)), '-', item)

0x69b164b0 - 1
0x12b2f00 - a
0x69ae14d0 - True
0x69ad7b14 - None
0xbf92350 - 3.45
0x69b164b0 - 1


In [87]:
import array
A = array.array('i', [1, 2, 3, 4, 5])
print(A)

for item in A:
    print(hex(id(item)))

array('i', [1, 2, 3, 4, 5])
0x69b164b0
0x69b164c0
0x69b164d0
0x69b164e0
0x69b164f0


## 2. 기본적인 NumPy 배열 생성등

In [97]:
np.random.seed(0)
x = np.random.randint(10, size=10)
x

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [98]:
x[0], x[-1], x[::2]

(5, 4, array([5, 3, 7, 3, 2]))

In [100]:
y = np.random.randint(10, size=(4,3))
y

array([[8, 9, 4],
       [3, 0, 3],
       [5, 0, 2],
       [3, 8, 1]])

In [103]:
y[0][2], y[3][-2], y[3, 2], y[:2, ::2]

(4, 8, 1, array([[8, 4],
        [3, 3]]))

### 그런데, subarray의 경우, copy가 아니라 view를 돌려주는 것!

In [106]:
y_sub = y[:2, ::2]
y_sub[0, 1] = 20000
print(y_sub)
print(y)

[[    8 20000]
 [    3     3]]
[[    8     9 20000]
 [    3     0     3]
 [    5     0     2]
 [    3     8     1]]


In [115]:
y_reshp = y.reshape((1,y.size))
y_reshp

array([[    8,     9, 20000,     3,     0,     3,     5,     0,     2,
            3,     8,     1]])

## 3. UFunc!

In [122]:
import numpy as np

def compute_reciprocals(values):
    
    output = np.empty(len(values))
    for i, val in enumerate(values):
        output[i] = 1.0 / val
        
    return output

np.random.seed(0)
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [124]:
big_array = np.random.randint(1, 100, size=1000000)

In [125]:
%timeit compute_reciprocals(big_array)

6.08 s ± 714 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [126]:
%timeit (1.0 / big_array)

14.1 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 4. Aggregation

%%timeit

mean_each = np.mean(data, axis=0)

for i, avg in enumerate(mean_each):
    print(f'{i+1} th mean: {avg}')

## 5. Broadcasting

## 6. Comparison and Boolean Logic

## 7. Fancy Indexing

## 8. Sorting

## 9. Structured Array

# Wrap-Up

넘파이는
- 수치 데이터에 한해서
- 더 효율적인 데이터 타입과
- 더 빠른 집합처리를 가능케 하여

일반목적용 프로그래밍 언어인 파이썬을  
통계학 프로그래밍 언어까지 넘볼 수 있게 해주었다.  

보통은 통계용 전문 프로그래밍 언어가 따로 있어 왔다.  
현재도 R, Julia 등이 파이썬의 강력한 경쟁자이다.   

다음 이 시간에는,  
- 수치 데이터에 한해서가 아니라 문자/카테고리 데이터까지 포함하여
- np.array보다 더 일반화된 tabular 데이터 처리를 위한 타입을 제공하는

Pandas에 대해서 알아볼 예정이다